"""add allow_same_owner_matches to leagues

Revision ID: 3d9aedcfa439
Revises: 7f13dd94be81
Create Date: 2026-08-27 18:46:10.860917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9aedcfa439'
down_revision: Union[str, Sequence[str], None] = '7f13dd94be81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('allow_same_owner_matches', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'allow_same_owner_matches')
    # ### end Alembic commands ###
