"""add teams table

Revision ID: a5b197589bbb
Revises: 8a37b1f50d3e
Create Date: 2026-04-19 14:44:33.829006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b197589bbb'
down_revision: Union[str, Sequence[str], None] = '8a37b1f50d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('nom_stade', sa.String(), nullable=False),
    sa.Column('id_owner', sa.Integer(), nullable=False),
    sa.Column('id_league', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_league'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_owner'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'id_league')
    )
    op.create_index(op.f('ix_equipes_id'), 'equipes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipes_id'), table_name='equipes')
    op.drop_table('equipes')
    # ### end Alembic commands ###
