"""add hashed_password to players

Revision ID: bf2dd1bd2357
Revises: 789228c86c13
Create Date: 2026-04-16 16:10:42.212698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2dd1bd2357'
down_revision: Union[str, Sequence[str], None] = '789228c86c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'hashed_password')
    # ### end Alembic commands ###
