"""add sport_type to leagues

Revision ID: ee34ac74e16d
Revises: 185dd8f2e608
Create Date: 2026-05-13 17:45:54.261259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee34ac74e16d'
down_revision: Union[str, Sequence[str], None] = '185dd8f2e608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE sporttypeenum AS ENUM ('football', 'basketball')")
    op.add_column('leagues', sa.Column('sport_type', sa.Enum('football', 'basketball', name='sporttypeenum'), nullable=False, server_default='football'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'sport_type')
    op.execute("DROP TYPE sporttypeenum")
    # ### end Alembic commands ###
