"""add match table

Revision ID: f15c59b9b73c
Revises: 55baeae48415
Create Date: 2026-04-23 15:45:17.168990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15c59b9b73c'
down_revision: Union[str, Sequence[str], None] = '55baeae48415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_home_id', sa.Integer(), nullable=False),
    sa.Column('team_away_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'in_progress', 'finished', name='matchstate'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_away_id'], ['equipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_home_id'], ['equipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    # Étape 1 : supprimer la valeur par défaut
    op.alter_column('players', 'player_type',
            server_default=None)

    # Étape 2 : convertir VARCHAR → Enum
    op.alter_column('players', 'player_type',
            existing_type=sa.VARCHAR(),
            type_=sa.Enum('humain', 'ia', name='playertypeenum'),
            existing_nullable=False,
            postgresql_using='player_type::playertypeenum')

    # Étape 3 : remettre la valeur par défaut
    op.alter_column('players', 'player_type',
            server_default='humain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'player_type',
               existing_type=sa.Enum('humain', 'ia', name='playertypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'humain'::character varying"))
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
