"""Nombre de journée aux matchs

Revision ID: fb45ba9cb54c
Revises: ee34ac74e16d
Create Date: 2026-05-13 18:08:36.352376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb45ba9cb54c'
down_revision: Union[str, Sequence[str], None] = 'ee34ac74e16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('round_number', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'round_number')
    # ### end Alembic commands ###
