"""add total_journeys to leagues

Revision ID: 185dd8f2e608
Revises: f15c59b9b73c
Create Date: 2026-04-23 16:27:50.664385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185dd8f2e608'
down_revision: Union[str, Sequence[str], None] = 'f15c59b9b73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('total_journeys', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'total_journeys')
    # ### end Alembic commands ###
