"""add is_active league

Revision ID: 55baeae48415
Revises: 9b4ad281a8be
Create Date: 2026-04-21 18:22:03.376376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55baeae48415'
down_revision: Union[str, Sequence[str], None] = '9b4ad281a8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'is_active')
    # ### end Alembic commands ###
