"""modification feed_items ajout league id

Revision ID: 7f13dd94be81
Revises: 340a3097a803
Create Date: 2026-05-15 17:53:01.775942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f13dd94be81'
down_revision: Union[str, Sequence[str], None] = '340a3097a803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_items', sa.Column('league_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feed_items', 'leagues', ['league_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feed_items', type_='foreignkey')
    op.drop_column('feed_items', 'league_id')
    # ### end Alembic commands ###
