"""add player type

Revision ID: 9b4ad281a8be
Revises: b257c76f214c
Create Date: 2026-04-19 17:06:31.852375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4ad281a8be'
down_revision: Union[str, Sequence[str], None] = 'b257c76f214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    player_type_enum = sa.Enum('humain', 'ia', name='playertypeenum')
    player_type_enum.create(op.get_bind())
    op.add_column('players', sa.Column('player_type', player_type_enum, nullable=False, server_default='humain'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'player_type')
    # ### end Alembic commands ###
