"""add max_teams and max_per_player to leagues

Revision ID: b257c76f214c
Revises: a5b197589bbb
Create Date: 2026-04-19 15:18:19.038121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b257c76f214c'
down_revision: Union[str, Sequence[str], None] = 'a5b197589bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('max_team', sa.Integer(), nullable=False))
    op.add_column('leagues', sa.Column('max_per_player', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'max_per_player')
    op.drop_column('leagues', 'max_team')
    # ### end Alembic commands ###
