"""suppression unicité du nom de ligue

Revision ID: bc2f72d17c20
Revises: b94fc8dada0e
Create Date: 2026-10-06 21:49:10.542606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2f72d17c20'
down_revision: Union[str, Sequence[str], None] = 'b94fc8dada0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leagues_name_key'), 'leagues', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('leagues_name_key'), 'leagues', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
